[project]
name = "likelion-pawong"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "numpy>=2.2.4",
    "uvicorn>=0.34.1",
]
